#!/bin/bash -l

#$ -cwd
#$ -P bf528
#$ -pe mpi_16_tasks_per_node 16
#$ -l h_rt=48:00:00

#$ -o run_tophat_anau.stdout
#$ -e run_tophat_anau.stderr

source /etc/bashrc
module load cufflinks

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Current time: $(date +%T)"
echo "Running in directory: $PWD"

P0BAM=/projectnb2/bf528/users/dachshund/project5_anau/P0_1_tophat/accepted_hits.bam

SAMPLEDIR=/project/bf528/project_2/data/samples/
P0REPS=$P0BAM,$SAMPLEDIR/P0_2/accepted_hits.bam
ADREPS=$SAMPLEDIR/Ad_1/accepted_hits.bam,$SAMPLEDIR/Ad_2/accepted_hits.bam

LABEL="P0,Ad"
OUTDIR=cuffdiff_out
FASTA=/project/bf528/project_2/reference/mm9.fa

cuffdiff -p 16 -L $LABEL -u -b $FASTA -o $OUTDIR $SAMPLEDIR/merged_asm/merged.gtf $P0REPS $ADREPS

echo "Job finished: $(date +%F)"
echo "Current time: $(date +%T)"
