#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -pe mpi_16_tasks_per_node 16

#$ -o run_tophat_anau.stdout
#$ -e run_tophat_anau.stderr

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Current time: $(date +%T)"
echo "Running in directory: $PWD"

#modules
module load python2
module load samtools/0.1.19
module load bowtie2
module load boost
module load tophat


# Variables
text1=/projectnb2/bf528/users/dachshund/project_2/project-2-project-2-dachsund/data/P0_1_1.fastq
text2=/projectnb2/bf528/users/dachshund/project_2/project-2-project-2-dachsund/data/P0_1_2.fastq
ref1=/project/bf528/project_2/reference/annot/mm9.gtf
ref2=/project/bf528/project_2/reference/mm9

#Arguments copied from /project/bf528/project_2/scripts/tophat_args.txt
tophat -r 200 -G $ref1 --segment-length=20 --segment-mismatches=1 --no-novel-juncs -o P0_1_tophat -p 16 $ref2 $text1 $text2

echo "Job finished: $(date +%F)"
echo "Current time: $(date +%T)"
